package net.voidhttp.request;

public enum ReadState {
    HEADERS_START,
    HEADERS_CONTINUE,
    HEADERS_PARSE,

    SIZED_CONTENT_START,
    SIZED_CONTENT_CONTINUE,
    SIZED_CONTENT_PARSE,

    MULTI_PART_CONTENT_START,
    MULTI_PART_CONTENT_CONTINUE,
    MULTI_PART_CONTENT_PARSE,
}
